/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "card-deck": {
    name: "card-deck",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/card-deck.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/card-deck.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition": {
    name: "admonition",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/admonition.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/admonition.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "orb": {
    name: "orb",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/orb.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/orb.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waveform": {
    name: "waveform",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/waveform.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/waveform.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "live-waveform": {
    name: "live-waveform",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/live-waveform.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/live-waveform.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/shimmering-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/shimmering-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "audio-player": {
    name: "audio-player",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/delta-ui/ui/audio-player.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/audio-player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "message": {
    name: "message",
    description: "",
    type: "registry:ui",
    registryDependencies: ["avatar"],
    files: [{
      path: "registry/delta-ui/ui/message.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/message.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation": {
    name: "conversation",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/delta-ui/ui/conversation.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/conversation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "response": {
    name: "response",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/response.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/response.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-visualizer": {
    name: "bar-visualizer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/bar-visualizer.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/bar-visualizer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-picker": {
    name: "voice-picker",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","badge","command","popover","https://deltacomponents.dev/r/orb.json","https://deltacomponents.dev/r/audio-player.json"],
    files: [{
      path: "registry/delta-ui/ui/voice-picker.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/voice-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-button": {
    name: "voice-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","https://deltacomponents.dev/r/live-waveform.json"],
    files: [{
      path: "registry/delta-ui/ui/voice-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/voice-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-bar": {
    name: "conversation-bar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","https://deltacomponents.dev/r/live-waveform.json","card","separator","textarea"],
    files: [{
      path: "registry/delta-ui/ui/conversation-bar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/conversation-bar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "x-scrollable": {
    name: "x-scrollable",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/x-scrollable.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/x-scrollable.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: ["x-scrollable"],
    files: [{
      path: "registry/delta-ui/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/tabs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "speaker-01": {
    name: "speaker-01",
    description: "EL-01 Speaker",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/audio-player.json","https://deltacomponents.dev/r/orb.json","waveform","button","card"],
    files: [{
      path: "registry/delta-ui/blocks/speaker-01/page.tsx",
      type: "registry:page",
      target: "app/speaker/page.tsx"
    },{
      path: "registry/delta-ui/blocks/speaker-01/components/speaker.tsx",
      type: "registry:component",
      target: "components/speaker.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/speaker-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"900px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "transcriber-01": {
    name: "transcriber-01",
    description: "Transcriber",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/live-waveform.json","button","card","scroll-area","separator"],
    files: [{
      path: "registry/delta-ui/blocks/transcriber-01/page.tsx",
      type: "registry:page",
      target: "app/transcriber-01/page.tsx"
    },{
      path: "registry/delta-ui/blocks/transcriber-01/actions/transcribe.ts",
      type: "registry:file",
      target: "app/transcriber-01/actions/transcribe.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/transcriber-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-chat-01": {
    name: "voice-chat-01",
    description: "Voice chat 1",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/orb.json","https://deltacomponents.dev/r/shimmering-text.json","button","card","https://deltacomponents.dev/r/message.json","https://deltacomponents.dev/r/response.json","https://deltacomponents.dev/r/conversation.json","scroll-area"],
    files: [{
      path: "registry/delta-ui/blocks/voice-chat-01/page.tsx",
      type: "registry:page",
      target: "app/voice-chat/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/voice-chat-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["agents"],
    meta: {"iframeHeight":"800px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-chat-02": {
    name: "voice-chat-02",
    description: "Voice chat 2",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/orb.json","https://deltacomponents.dev/r/shimmering-text.json","button","card"],
    files: [{
      path: "registry/delta-ui/blocks/voice-chat-02/page.tsx",
      type: "registry:page",
      target: "app/voice-chat/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/voice-chat-02/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["agents"],
    meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-chat-03": {
    name: "voice-chat-03",
    description: "Voice chat 3",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/conversation-bar.json","https://deltacomponents.dev/r/conversation.json","https://deltacomponents.dev/r/message.json","https://deltacomponents.dev/r/orb.json","https://deltacomponents.dev/r/response.json","tooltip","card","button"],
    files: [{
      path: "registry/delta-ui/blocks/voice-chat-03/page.tsx",
      type: "registry:page",
      target: "app/voice-chat/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/voice-chat-03/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["agents"],
    meta: {"iframeHeight":"800px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "music-player-01": {
    name: "music-player-01",
    description: "Music player with playlist",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/audio-player.json","button","scroll-area"],
    files: [{
      path: "registry/delta-ui/blocks/music-player-01/page.tsx",
      type: "registry:page",
      target: "app/music-player/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/music-player-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "music-player-02": {
    name: "music-player-02",
    description: "Simple music player",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/audio-player.json","card"],
    files: [{
      path: "registry/delta-ui/blocks/music-player-02/page.tsx",
      type: "registry:page",
      target: "app/music-player/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/music-player-02/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"400px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-form-01": {
    name: "voice-form-01",
    description: "Voice-fill form",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/voice-button.json","https://deltacomponents.dev/r/live-waveform.json","button","card","form","input"],
    files: [{
      path: "registry/delta-ui/blocks/voice-form-01/page.tsx",
      type: "registry:page",
      target: "app/voice-form/page.tsx"
    },{
      path: "registry/delta-ui/blocks/voice-form-01/schema.ts",
      type: "registry:file",
      target: "app/voice-form/schema.ts"
    },{
      path: "registry/delta-ui/blocks/voice-form-01/actions/voice-to-form.ts",
      type: "registry:file",
      target: "app/voice-form/actions/voice-to-form.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/voice-form-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"700px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-nav-01": {
    name: "voice-nav-01",
    description: "Voice-nav site navigation",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/voice-button.json","button","card"],
    files: [{
      path: "registry/delta-ui/blocks/voice-nav-01/page.tsx",
      type: "registry:page",
      target: "app/voice-nav/page.tsx"
    },{
      path: "registry/delta-ui/blocks/voice-nav-01/actions/voice-to-site.ts",
      type: "registry:file",
      target: "app/voice-nav/actions/voice-to-site.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/voice-nav-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"900px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "testimonials": {
    name: "testimonials",
    description: "Customer testimonials grid",
    type: "registry:block",
    registryDependencies: [],
    files: [{
      path: "registry/delta-ui/blocks/testimonials/page.tsx",
      type: "registry:page",
      target: "app/testimonials/page.tsx"
    },{
      path: "registry/delta-ui/blocks/testimonials/components/testimonials.tsx",
      type: "registry:component",
      target: "components/testimonials.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/testimonials/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["landing-page"],
    meta: {"iframeHeight":"800px","container":"w-full bg-background min-h-svh flex items-center justify-center","mobile":"component"},
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/hooks/use-mobile.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-demo": {
    name: "card-deck-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-demo-interactive": {
    name: "card-deck-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition-demo": {
    name: "admonition-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    files: [{
      path: "registry/delta-ui/examples/admonition-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/admonition-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition-demo-interactive": {
    name: "admonition-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    files: [{
      path: "registry/delta-ui/examples/admonition-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/admonition-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "audio-player-demo": {
    name: "audio-player-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/audio-player.json","button","card","scroll-area"],
    files: [{
      path: "registry/delta-ui/examples/audio-player-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/audio-player-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "orb-demo": {
    name: "orb-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/orb.json","button"],
    files: [{
      path: "registry/delta-ui/examples/orb-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/orb-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waveform-demo": {
    name: "waveform-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["waveform"],
    files: [{
      path: "registry/delta-ui/examples/waveform-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/waveform-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "live-waveform-demo": {
    name: "live-waveform-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/live-waveform.json","button"],
    files: [{
      path: "registry/delta-ui/examples/live-waveform-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/live-waveform-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-visualizer-demo": {
    name: "bar-visualizer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/bar-visualizer.json","button"],
    files: [{
      path: "registry/delta-ui/examples/bar-visualizer-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/bar-visualizer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "message-demo": {
    name: "message-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/message.json","https://deltacomponents.dev/r/response.json"],
    files: [{
      path: "registry/delta-ui/examples/message-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/message-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "response-demo": {
    name: "response-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/response.json"],
    files: [{
      path: "registry/delta-ui/examples/response-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/response-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text-demo": {
    name: "shimmering-text-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/shimmering-text.json"],
    files: [{
      path: "registry/delta-ui/examples/shimmering-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/shimmering-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-picker-demo": {
    name: "voice-picker-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/voice-picker.json","https://deltacomponents.dev/r/audio-player.json"],
    files: [{
      path: "registry/delta-ui/examples/voice-picker-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/voice-picker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-button-demo": {
    name: "voice-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/voice-button.json"],
    files: [{
      path: "registry/delta-ui/examples/voice-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/voice-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-bar-demo": {
    name: "conversation-bar-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/conversation-bar.json"],
    files: [{
      path: "registry/delta-ui/examples/conversation-bar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/conversation-bar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-demo": {
    name: "conversation-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/message.json","https://deltacomponents.dev/r/response.json","https://deltacomponents.dev/r/conversation.json"],
    files: [{
      path: "registry/delta-ui/examples/conversation-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/conversation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-demo": {
    name: "tabs-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "registry/delta-ui/examples/tabs-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }