/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "cambio-image": {
    name: "cambio-image",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/cambio-image.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/cambio-image.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck": {
    name: "card-deck",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/card-deck.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/card-deck.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition": {
    name: "admonition",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/admonition.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/admonition.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "x-scrollable": {
    name: "x-scrollable",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/ui/x-scrollable.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/x-scrollable.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: ["x-scrollable"],
    files: [{
      path: "registry/delta-ui/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/ui/tabs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonials": {
    name: "testimonials",
    description: "Customer testimonials grid",
    type: "registry:block",
    registryDependencies: [],
    files: [{
      path: "registry/delta-ui/blocks/testimonials/page.tsx",
      type: "registry:page",
      target: "app/testimonials/page.tsx"
    },{
      path: "registry/delta-ui/blocks/testimonials/components/testimonials.tsx",
      type: "registry:component",
      target: "components/testimonials.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/testimonials/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["landing-page"],
    meta: {"iframeHeight":"800px","container":"w-full bg-background min-h-svh flex items-center justify-center","mobile":"component"},
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/hooks/use-mobile.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "cambio-image-demo": {
    name: "cambio-image-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/cambio-image.json"],
    files: [{
      path: "registry/delta-ui/examples/cambio-image-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/cambio-image-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "cambio-image-grid-demo": {
    name: "cambio-image-grid-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/cambio-image.json"],
    files: [{
      path: "registry/delta-ui/examples/cambio-image-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/cambio-image-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-demo": {
    name: "qrcode-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-purple-dots-demo": {
    name: "qrcode-purple-dots-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-purple-dots-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-purple-dots-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-demo-interactive": {
    name: "qrcode-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-demo": {
    name: "card-deck-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-demo-interactive": {
    name: "card-deck-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition-demo": {
    name: "admonition-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    files: [{
      path: "registry/delta-ui/examples/admonition-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/admonition-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition-demo-interactive": {
    name: "admonition-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    files: [{
      path: "registry/delta-ui/examples/admonition-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/admonition-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-demo": {
    name: "tabs-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "registry/delta-ui/examples/tabs-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-stack-yugioh-demo": {
    name: "card-stack-yugioh-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-stack-yugioh-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-stack-yugioh-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }