/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "code-block": {
    name: "code-block",
    description: "",
    type: "registry:ui",
    registryDependencies: ["copy-button"],
    files: [{
      path: "registry/delta-ui/delta/code-block.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/code-block.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","tooltip"],
    files: [{
      path: "registry/delta-ui/delta/copy-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "cambio-image": {
    name: "cambio-image",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/delta/cambio-image.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/cambio-image.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck": {
    name: "card-deck",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/delta/card-deck.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/card-deck.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition": {
    name: "admonition",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/delta/admonition.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/admonition.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "x-scrollable": {
    name: "x-scrollable",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/delta/x-scrollable.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/x-scrollable.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: ["x-scrollable"],
    files: [{
      path: "registry/delta-ui/delta/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/tabs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode": {
    name: "qrcode",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/delta/qrcode.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/qrcode.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chat": {
    name: "chat",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","avatar","textarea","select"],
    files: [{
      path: "registry/delta-ui/examples/chat-demo.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/chat-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mapbox-pointer": {
    name: "mapbox-pointer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/delta/mapbox-pointer.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/delta/mapbox-pointer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonials": {
    name: "testimonials",
    description: "Customer testimonials grid",
    type: "registry:block",
    registryDependencies: [],
    files: [{
      path: "registry/delta-ui/blocks/testimonials/page.tsx",
      type: "registry:page",
      target: "app/testimonials/page.tsx"
    },{
      path: "registry/delta-ui/blocks/testimonials/components/testimonials.tsx",
      type: "registry:component",
      target: "components/testimonials.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/testimonials/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["landing-page"],
    meta: {"iframeHeight":"800px","container":"w-full bg-background min-h-svh flex items-center justify-center","mobile":"component"},
  },
  "interactive-feature-showcase": {
    name: "interactive-feature-showcase",
    description: "InteractiveFeatureShowcase block",
    type: "registry:block",
    registryDependencies: [],
    files: [{
      path: "registry/delta-ui/blocks/interactive-feature-showcase/page.tsx",
      type: "registry:page",
      target: "app/interactive-feature-showcase/page.tsx"
    },{
      path: "registry/delta-ui/blocks/interactive-feature-showcase/components/interactive-feature-showcase.tsx",
      type: "registry:component",
      target: "components/interactive-feature-showcase.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/interactive-feature-showcase/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["landing-page"],
    meta: {"iframeHeight":"800px","container":"w-full","mobile":"component"},
  },
  "chatbot-window": {
    name: "chatbot-window",
    description: "Resizable AI chatbot interface with collapsible sidebar",
    type: "registry:block",
    registryDependencies: ["button","avatar","select","textarea","resizable"],
    files: [{
      path: "registry/delta-ui/blocks/chatbot-window/page.tsx",
      type: "registry:page",
      target: "app/chatbot-window/page.tsx"
    },{
      path: "registry/delta-ui/blocks/chatbot-window/components/chatbot-window.tsx",
      type: "registry:component",
      target: "components/chatbot-window.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/chatbot-window/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["ai-elements","featured"],
    meta: {"iframeHeight":"800px","container":"w-full h-screen","mobile":"component"},
  },
  "perspective-carousel": {
    name: "perspective-carousel",
    description: "PerspectiveCarousel block",
    type: "registry:block",
    registryDependencies: [],
    files: [{
      path: "registry/delta-ui/blocks/perspective-carousel/page.tsx",
      type: "registry:page",
      target: "app/perspective-carousel/page.tsx"
    },{
      path: "registry/delta-ui/blocks/perspective-carousel/components/perspective-carousel.tsx",
      type: "registry:component",
      target: "components/perspective-carousel.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/blocks/perspective-carousel/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["featured"],
    meta: {"iframeHeight":"600px","container":"w-full","mobile":"component"},
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/delta-ui/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/hooks/use-mobile.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mapbox-pointer-demo": {
    name: "mapbox-pointer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/mapbox-pointer.json"],
    files: [{
      path: "registry/delta-ui/examples/mapbox-pointer-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/mapbox-pointer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mapbox-pointer-style-demo": {
    name: "mapbox-pointer-style-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/mapbox-pointer.json"],
    files: [{
      path: "registry/delta-ui/examples/mapbox-pointer-style-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/mapbox-pointer-style-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chat-demo": {
    name: "chat-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/chat.json"],
    files: [{
      path: "registry/delta-ui/examples/chat-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/chat-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chat-previous-messages-demo": {
    name: "chat-previous-messages-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/chat.json"],
    files: [{
      path: "registry/delta-ui/examples/chat-previous-messages-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/chat-previous-messages-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chat-simple-demo": {
    name: "chat-simple-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/chat.json"],
    files: [{
      path: "registry/delta-ui/examples/chat-simple-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/chat-simple-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-demo": {
    name: "code-block-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/code-block.json"],
    files: [{
      path: "registry/delta-ui/examples/code-block-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/code-block-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-package-demo": {
    name: "code-block-package-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/code-block.json"],
    files: [{
      path: "registry/delta-ui/examples/code-block-package-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/code-block-package-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-theme-demo": {
    name: "code-block-theme-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/code-block.json","https://deltacomponents.dev/r/button.json"],
    files: [{
      path: "registry/delta-ui/examples/code-block-theme-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/code-block-theme-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-interactive-demo": {
    name: "code-block-interactive-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/code-block.json"],
    files: [{
      path: "registry/delta-ui/examples/code-block-interactive-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/code-block-interactive-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "cambio-image-demo": {
    name: "cambio-image-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/cambio-image.json"],
    files: [{
      path: "registry/delta-ui/examples/cambio-image-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/cambio-image-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "cambio-image-grid-demo": {
    name: "cambio-image-grid-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/cambio-image.json"],
    files: [{
      path: "registry/delta-ui/examples/cambio-image-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/cambio-image-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-demo": {
    name: "qrcode-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-purple-dots-demo": {
    name: "qrcode-purple-dots-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-purple-dots-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-purple-dots-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-demo-interactive": {
    name: "qrcode-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "qrcode-logo-demo": {
    name: "qrcode-logo-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/qrcode.json"],
    files: [{
      path: "registry/delta-ui/examples/qrcode-logo-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/qrcode-logo-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-demo": {
    name: "card-deck-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-demo-interactive": {
    name: "card-deck-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition-demo": {
    name: "admonition-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    files: [{
      path: "registry/delta-ui/examples/admonition-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/admonition-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "admonition-demo-interactive": {
    name: "admonition-demo-interactive",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    files: [{
      path: "registry/delta-ui/examples/admonition-demo-interactive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/admonition-demo-interactive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-demo": {
    name: "tabs-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "registry/delta-ui/examples/tabs-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-yugioh-demo": {
    name: "card-deck-yugioh-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-yugioh-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-yugioh-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-deck-balatro-demo": {
    name: "card-deck-balatro-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://deltacomponents.dev/r/card-deck.json"],
    files: [{
      path: "registry/delta-ui/examples/card-deck-balatro-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/delta-ui/examples/card-deck-balatro-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }