/* eslint-disable */
//
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "checkbox-input": {
    name: "checkbox-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","checkbox","input","validation","selection","toggle","accessible"],
    files: [
      {
        path: "registry/inputs/checkbox-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/checkbox-input")),
    source: "",
  },
  "radio-input": {
    name: "radio-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","radio","input","selection","options","accessible","multiple choice"],
    files: [
      {
        path: "registry/inputs/radio-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/radio-input")),
    source: "",
  },
  "date-input": {
    name: "date-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","date","input","calendar","time","datepicker","validation"],
    files: [
      {
        path: "registry/inputs/date-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/date-input")),
    source: "",
  },
  "switch-input": {
    name: "switch-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","switch","input","toggle","on-off","boolean","accessible"],
    files: [
      {
        path: "registry/inputs/switch-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/switch-input")),
    source: "",
  },
  "select-input": {
    name: "select-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","select","dropdown","options","input","validation","choice"],
    files: [
      {
        path: "registry/inputs/select-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/select-input")),
    source: "",
  },
  "tags-input": {
    name: "tags-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","tags","input","multiple","chips","keywords","interactive"],
    files: [
      {
        path: "registry/inputs/tags-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/tags-input")),
    source: "",
  },
  "textarea-input": {
    name: "textarea-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","textarea","multiline","input","text","validation","large text"],
    files: [
      {
        path: "registry/inputs/textarea-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/textarea-input")),
    source: "",
  },
  "file-input": {
    name: "file-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","file","upload","input","attachment","drag-and-drop","validation"],
    files: [
      {
        path: "registry/inputs/file-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/file-input")),
    source: "",
  },
  "otp-input": {
    name: "otp-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","otp","verification","code","input","auth","secure"],
    files: [
      {
        path: "registry/inputs/otp-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/otp-input")),
    source: "",
  },
  "text-input": {
    name: "text-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","text","input","validation","single-line","accessible","field"],
    files: [
      {
        path: "registry/inputs/text-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/text-input")),
    source: "",
  },
  "highlighter-demo": {
    name: "highlighter-demo",
    type: "registry:block",
    registryDependencies: ["highlighter"],
    tags: [],
    files: [
      {
        path: "registry/examples/highlighter-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/highlighter-demo")),
    source: "",
  },
  "backdrop-gradient-demo": {
    name: "backdrop-gradient-demo",
    type: "registry:block",
    registryDependencies: ["backdrop-gradient"],
    tags: [],
    files: [
      {
        path: "registry/examples/backdrop-gradient-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/backdrop-gradient-demo")),
    source: "",
  },
  "smart-form-demo": {
    name: "smart-form-demo",
    type: "registry:block",
    registryDependencies: ["smart-form"],
    tags: [],
    files: [
      {
        path: "registry/examples/smart-form-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/smart-form-demo")),
    source: "",
  },
  "checkbox-input-demo": {
    name: "checkbox-input-demo",
    type: "registry:block",
    registryDependencies: ["checkbox-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/checkbox-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/checkbox-input-demo")),
    source: "",
  },
  "radio-input-demo": {
    name: "radio-input-demo",
    type: "registry:block",
    registryDependencies: ["radio-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/radio-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/radio-input-demo")),
    source: "",
  },
  "date-input-demo": {
    name: "date-input-demo",
    type: "registry:block",
    registryDependencies: ["date-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/date-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/date-input-demo")),
    source: "",
  },
  "switch-input-demo": {
    name: "switch-input-demo",
    type: "registry:block",
    registryDependencies: ["switch-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/switch-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/switch-input-demo")),
    source: "",
  },
  "select-input-demo": {
    name: "select-input-demo",
    type: "registry:block",
    registryDependencies: ["select-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/select-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/select-input-demo")),
    source: "",
  },
  "tags-input-demo": {
    name: "tags-input-demo",
    type: "registry:block",
    registryDependencies: ["tags-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/tags-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tags-input-demo")),
    source: "",
  },
  "textarea-input-demo": {
    name: "textarea-input-demo",
    type: "registry:block",
    registryDependencies: ["textarea-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/textarea-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/textarea-input-demo")),
    source: "",
  },
  "retro-video-player-demo": {
    name: "retro-video-player-demo",
    type: "registry:block",
    registryDependencies: ["retro-video-player"],
    tags: [],
    files: [
      {
        path: "registry/examples/retro-video-player-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/retro-video-player-demo")),
    source: "",
  },
  "code-block-demo": {
    name: "code-block-demo",
    type: "registry:block",
    registryDependencies: ["code-block"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-block-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-block-demo")),
    source: "",
  },
  "drawer-demo": {
    name: "drawer-demo",
    type: "registry:block",
    registryDependencies: ["drawer"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-demo")),
    source: "",
  },
  "modal-demo": {
    name: "modal-demo",
    type: "registry:block",
    registryDependencies: ["modal"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-demo")),
    source: "",
  },
  "tabs-demo": {
    name: "tabs-demo",
    type: "registry:block",
    registryDependencies: ["tabs","x-scrollable"],
    tags: [],
    files: [
      {
        path: "registry/examples/tabs-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tabs-demo")),
    source: "",
  },
  "scramble-text-demo": {
    name: "scramble-text-demo",
    type: "registry:block",
    registryDependencies: ["scramble-text"],
    tags: [],
    files: [
      {
        path: "registry/examples/scramble-text-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/scramble-text-demo")),
    source: "",
  },
  "use-copy-to-clipboard-demo": {
    name: "use-copy-to-clipboard-demo",
    type: "registry:block",
    registryDependencies: ["use-copy-to-clipboard"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-copy-to-clipboard-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-copy-to-clipboard-demo")),
    source: "",
  },
  "use-interval-demo": {
    name: "use-interval-demo",
    type: "registry:block",
    registryDependencies: ["use-interval"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-interval-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-interval-demo")),
    source: "",
  },
  "use-timeout-demo": {
    name: "use-timeout-demo",
    type: "registry:block",
    registryDependencies: ["use-timeout"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-timeout-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-timeout-demo")),
    source: "",
  },
  "use-document-title-demo": {
    name: "use-document-title-demo",
    type: "registry:block",
    registryDependencies: ["use-document-title"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-document-title-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-document-title-demo")),
    source: "",
  },
  "use-mouse-position-demo": {
    name: "use-mouse-position-demo",
    type: "registry:block",
    registryDependencies: ["use-mouse-position"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-mouse-position-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-mouse-position-demo")),
    source: "",
  },
  "otp-input-demo": {
    name: "otp-input-demo",
    type: "registry:block",
    registryDependencies: ["otp-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-demo")),
    source: "",
  },
  "text-input-demo": {
    name: "text-input-demo",
    type: "registry:block",
    registryDependencies: ["text-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/text-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/text-input-demo")),
    source: "",
  },
  "file-input-demo": {
    name: "file-input-demo",
    type: "registry:block",
    registryDependencies: ["file-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/file-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/file-input-demo")),
    source: "",
  },
  "tabs-spotify-demo": {
    name: "tabs-spotify-demo",
    type: "registry:block",
    registryDependencies: ["tabs","x-scrollable"],
    tags: [],
    files: [
      {
        path: "registry/examples/tabs-spotify-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tabs-spotify-demo")),
    source: "",
  },
  "drawer-modern-demo": {
    name: "drawer-modern-demo",
    type: "registry:block",
    registryDependencies: ["drawer"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-modern-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-modern-demo")),
    source: "",
  },
  "backdrop-gradient-artistic-demo": {
    name: "backdrop-gradient-artistic-demo",
    type: "registry:block",
    registryDependencies: ["backdrop-gradient"],
    tags: [],
    files: [
      {
        path: "registry/examples/backdrop-gradient-artistic-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/backdrop-gradient-artistic-demo")),
    source: "",
  },
  "x-scrollable-colorful-demo": {
    name: "x-scrollable-colorful-demo",
    type: "registry:block",
    registryDependencies: ["x-scrollable"],
    tags: [],
    files: [
      {
        path: "registry/examples/x-scrollable-colorful-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/x-scrollable-colorful-demo")),
    source: "",
  },
  "smart-form-pill-demo": {
    name: "smart-form-pill-demo",
    type: "registry:block",
    registryDependencies: ["smart-form"],
    tags: [],
    files: [
      {
        path: "registry/examples/smart-form-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/smart-form-pill-demo")),
    source: "",
  },
  "scramble-text": {
    name: "scramble-text",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["animation","text","scramble","effect","motion","interaction","reveal"],
    files: [
      {
        path: "registry/animations/scramble-text.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/animations/scramble-text")),
    source: "",
  },
  "drawer": {
    name: "drawer",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["overlay","panel","slide","bottom sheet","dialog","mobile","responsive"],
    files: [
      {
        path: "registry/components/drawer.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/drawer")),
    source: "",
  },
  "modal": {
    name: "modal",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["dialog","popup","overlay","animated","accessible","responsive"],
    files: [
      {
        path: "registry/components/modal.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/modal")),
    source: "",
  },
  "tabs": {
    name: "tabs",
    type: "registry:component",
    registryDependencies: ["x-scrollable"],
    tags: ["navigation","tabs","interactive","animated","scrollable","content switcher"],
    files: [
      {
        path: "registry/components/tabs.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/tabs")),
    source: "",
  },
  "x-scrollable": {
    name: "x-scrollable",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["scroll","horizontal","container","utility","overflow","layout"],
    files: [
      {
        path: "registry/components/x-scrollable.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/x-scrollable")),
    source: "",
  },
  "smart-form": {
    name: "smart-form",
    type: "registry:block",
    registryDependencies: ["text-input","checkbox-input","select-input","radio-input","switch-input","textarea-input","date-input","file-input","otp-input","tags-input"],
    tags: ["form","dynamic","smart","validation","reactive","data collection","AI"],
    files: [
      {
        path: "registry/blocks/smart-form.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/blocks/smart-form")),
    source: "",
  },
  "highlighter": {
    name: "highlighter",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/landing-page/highlighter.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/landing-page/highlighter")),
    source: "",
  },
  "backdrop-gradient": {
    name: "backdrop-gradient",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["effect","image","blur","gradient","background","filter"],
    files: [
      {
        path: "registry/media/backdrop-gradient.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/backdrop-gradient")),
    source: "",
  },
  "retro-video-player": {
    name: "retro-video-player",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["video","player","draggable","resizable","retro","ui","media"],
    files: [
      {
        path: "registry/media/retro-video-player.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/retro-video-player")),
    source: "",
  },
  "code-block": {
    name: "code-block",
    type: "registry:component",
    registryDependencies: ["button"],
    tags: ["syntax highlighting","code","copyable","expandable","theme-aware","developer"],
    files: [
      {
        path: "registry/media/code-block.tsx",
        type: "registry:component",
        target: "",
      },
      {
        path: "registry/media/code-block.css",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/code-block")),
    source: "",
  },
}
