/* eslint-disable */
//
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "checkbox-input": {
    name: "checkbox-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","checkbox","input","validation","selection","toggle","accessible"],
    files: [
      {
        path: "registry/inputs/checkbox-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/checkbox-input")),
    source: "",
  },
  "radio-input": {
    name: "radio-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","radio","input","selection","options","accessible","multiple choice"],
    files: [
      {
        path: "registry/inputs/radio-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/radio-input")),
    source: "",
  },
  "date-input": {
    name: "date-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","date","input","calendar","time","datepicker","validation"],
    files: [
      {
        path: "registry/inputs/date-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/date-input")),
    source: "",
  },
  "switch-input": {
    name: "switch-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","switch","input","toggle","on-off","boolean","accessible"],
    files: [
      {
        path: "registry/inputs/switch-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/switch-input")),
    source: "",
  },
  "select-input": {
    name: "select-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","select","dropdown","options","input","validation","choice"],
    files: [
      {
        path: "registry/inputs/select-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/select-input")),
    source: "",
  },
  "tags-input": {
    name: "tags-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","tags","input","multiple","chips","keywords","interactive"],
    files: [
      {
        path: "registry/inputs/tags-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/tags-input")),
    source: "",
  },
  "textarea-input": {
    name: "textarea-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","textarea","multiline","input","text","validation","large text"],
    files: [
      {
        path: "registry/inputs/textarea-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/textarea-input")),
    source: "",
  },
  "file-input": {
    name: "file-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","file","upload","input","attachment","drag-and-drop","validation"],
    files: [
      {
        path: "registry/inputs/file-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/file-input")),
    source: "",
  },
  "otp-input": {
    name: "otp-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","otp","verification","code","input","auth","secure"],
    files: [
      {
        path: "registry/inputs/otp-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/otp-input")),
    source: "",
  },
  "text-input": {
    name: "text-input",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["form","text","input","validation","single-line","accessible","field"],
    files: [
      {
        path: "registry/inputs/text-input.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/inputs/text-input")),
    source: "",
  },
  "use-mobile-demo": {
    name: "use-mobile-demo",
    type: "registry:block",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/examples/use-mobile-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-mobile-demo")),
    source: "",
  },
  "youtube-demo": {
    name: "youtube-demo",
    type: "registry:block",
    registryDependencies: ["youtube"],
    tags: [],
    files: [
      {
        path: "registry/examples/youtube-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/youtube-demo")),
    source: "",
  },
  "cambio-image-demo": {
    name: "cambio-image-demo",
    type: "registry:block",
    registryDependencies: ["cambio-image"],
    tags: [],
    files: [
      {
        path: "registry/examples/cambio-image-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/cambio-image-demo")),
    source: "",
  },
  "cambio-image-grid-demo": {
    name: "cambio-image-grid-demo",
    type: "registry:block",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/examples/cambio-image-grid-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/cambio-image-grid-demo")),
    source: "",
  },
  "cambio-image-accessible-demo": {
    name: "cambio-image-accessible-demo",
    type: "registry:block",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/examples/cambio-image-accessible-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/cambio-image-accessible-demo")),
    source: "",
  },
  "cambio-image-bouncy-demo": {
    name: "cambio-image-bouncy-demo",
    type: "registry:block",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/examples/cambio-image-bouncy-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/cambio-image-bouncy-demo")),
    source: "",
  },
  "cambio-image-snappy-demo": {
    name: "cambio-image-snappy-demo",
    type: "registry:block",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/examples/cambio-image-snappy-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/cambio-image-snappy-demo")),
    source: "",
  },
  "cambio-image-advanced-demo": {
    name: "cambio-image-advanced-demo",
    type: "registry:block",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/examples/cambio-image-advanced-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/cambio-image-advanced-demo")),
    source: "",
  },
  "marquee-demo": {
    name: "marquee-demo",
    type: "registry:block",
    registryDependencies: ["marquee"],
    tags: [],
    files: [
      {
        path: "registry/examples/marquee-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/marquee-demo")),
    source: "",
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    type: "registry:block",
    registryDependencies: ["dropdown-menu"],
    tags: [],
    files: [
      {
        path: "registry/examples/dropdown-menu-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/dropdown-menu-demo")),
    source: "",
  },
  "header-sleek-demo": {
    name: "header-sleek-demo",
    type: "registry:block",
    registryDependencies: ["header-sleek"],
    tags: [],
    files: [
      {
        path: "registry/examples/header-sleek-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/header-sleek-demo")),
    source: "",
  },
  "social-icons-demo": {
    name: "social-icons-demo",
    type: "registry:block",
    registryDependencies: ["social-icons"],
    tags: [],
    files: [
      {
        path: "registry/examples/social-icons-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/social-icons-demo")),
    source: "",
  },
  "animate-in-demo": {
    name: "animate-in-demo",
    type: "registry:block",
    registryDependencies: ["animate-in"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-demo")),
    source: "",
  },
  "footer-demo": {
    name: "footer-demo",
    type: "registry:block",
    registryDependencies: ["footer"],
    tags: [],
    files: [
      {
        path: "registry/examples/footer-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/footer-demo")),
    source: "",
  },
  "mouse-string-connection-demo": {
    name: "mouse-string-connection-demo",
    type: "registry:block",
    registryDependencies: ["mouse-string-connection"],
    tags: [],
    files: [
      {
        path: "registry/examples/mouse-string-connection-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/mouse-string-connection-demo")),
    source: "",
  },
  "font-transform-demo": {
    name: "font-transform-demo",
    type: "registry:block",
    registryDependencies: ["font-transform"],
    tags: [],
    files: [
      {
        path: "registry/examples/font-transform-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/font-transform-demo")),
    source: "",
  },
  "pricing-cards-demo": {
    name: "pricing-cards-demo",
    type: "registry:block",
    registryDependencies: ["pricing-cards"],
    tags: [],
    files: [
      {
        path: "registry/examples/pricing-cards-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/pricing-cards-demo")),
    source: "",
  },
  "floating-object-demo": {
    name: "floating-object-demo",
    type: "registry:block",
    registryDependencies: ["floating-object"],
    tags: [],
    files: [
      {
        path: "registry/examples/floating-object-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/floating-object-demo")),
    source: "",
  },
  "qr-code-demo": {
    name: "qr-code-demo",
    type: "registry:block",
    registryDependencies: ["qr-code"],
    tags: [],
    files: [
      {
        path: "registry/examples/qr-code-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/qr-code-demo")),
    source: "",
  },
  "spotify-demo": {
    name: "spotify-demo",
    type: "registry:block",
    registryDependencies: ["spotify"],
    tags: [],
    files: [
      {
        path: "registry/examples/spotify-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/spotify-demo")),
    source: "",
  },
  "star-rating-demo": {
    name: "star-rating-demo",
    type: "registry:block",
    registryDependencies: ["star-rating"],
    tags: [],
    files: [
      {
        path: "registry/examples/star-rating-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/star-rating-demo")),
    source: "",
  },
  "retro-button-demo": {
    name: "retro-button-demo",
    type: "registry:block",
    registryDependencies: ["retro-button"],
    tags: [],
    files: [
      {
        path: "registry/examples/retro-button-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/retro-button-demo")),
    source: "",
  },
  "admonition-demo": {
    name: "admonition-demo",
    type: "registry:block",
    registryDependencies: ["admonition"],
    tags: [],
    files: [
      {
        path: "registry/examples/admonition-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/admonition-demo")),
    source: "",
  },
  "embed-demo": {
    name: "embed-demo",
    type: "registry:block",
    registryDependencies: ["embed"],
    tags: [],
    files: [
      {
        path: "registry/examples/embed-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/embed-demo")),
    source: "",
  },
  "scroll-progress-demo": {
    name: "scroll-progress-demo",
    type: "registry:block",
    registryDependencies: ["scroll-progress"],
    tags: [],
    files: [
      {
        path: "registry/examples/scroll-progress-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/scroll-progress-demo")),
    source: "",
  },
  "scroll-progress-article-demo": {
    name: "scroll-progress-article-demo",
    type: "registry:block",
    registryDependencies: ["scroll-progress"],
    tags: [],
    files: [
      {
        path: "registry/examples/scroll-progress-article-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/scroll-progress-article-demo")),
    source: "",
  },
  "highlighter-demo": {
    name: "highlighter-demo",
    type: "registry:block",
    registryDependencies: ["highlighter"],
    tags: [],
    files: [
      {
        path: "registry/examples/highlighter-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/highlighter-demo")),
    source: "",
  },
  "backdrop-gradient-demo": {
    name: "backdrop-gradient-demo",
    type: "registry:block",
    registryDependencies: ["backdrop-gradient"],
    tags: [],
    files: [
      {
        path: "registry/examples/backdrop-gradient-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/backdrop-gradient-demo")),
    source: "",
  },
  "smart-form-demo": {
    name: "smart-form-demo",
    type: "registry:block",
    registryDependencies: ["smart-form"],
    tags: [],
    files: [
      {
        path: "registry/examples/smart-form-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/smart-form-demo")),
    source: "",
  },
  "checkbox-input-demo": {
    name: "checkbox-input-demo",
    type: "registry:block",
    registryDependencies: ["checkbox-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/checkbox-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/checkbox-input-demo")),
    source: "",
  },
  "radio-input-demo": {
    name: "radio-input-demo",
    type: "registry:block",
    registryDependencies: ["radio-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/radio-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/radio-input-demo")),
    source: "",
  },
  "date-input-demo": {
    name: "date-input-demo",
    type: "registry:block",
    registryDependencies: ["date-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/date-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/date-input-demo")),
    source: "",
  },
  "switch-input-demo": {
    name: "switch-input-demo",
    type: "registry:block",
    registryDependencies: ["switch-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/switch-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/switch-input-demo")),
    source: "",
  },
  "select-input-demo": {
    name: "select-input-demo",
    type: "registry:block",
    registryDependencies: ["select-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/select-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/select-input-demo")),
    source: "",
  },
  "tags-input-demo": {
    name: "tags-input-demo",
    type: "registry:block",
    registryDependencies: ["tags-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/tags-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tags-input-demo")),
    source: "",
  },
  "textarea-input-demo": {
    name: "textarea-input-demo",
    type: "registry:block",
    registryDependencies: ["textarea-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/textarea-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/textarea-input-demo")),
    source: "",
  },
  "retro-video-player-demo": {
    name: "retro-video-player-demo",
    type: "registry:block",
    registryDependencies: ["retro-video-player"],
    tags: [],
    files: [
      {
        path: "registry/examples/retro-video-player-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/retro-video-player-demo")),
    source: "",
  },
  "code-snippet-demo": {
    name: "code-snippet-demo",
    type: "registry:block",
    registryDependencies: ["code-snippet"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-snippet-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-snippet-demo")),
    source: "",
  },
  "drawer-demo": {
    name: "drawer-demo",
    type: "registry:block",
    registryDependencies: ["drawer"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-demo")),
    source: "",
  },
  "modal-demo": {
    name: "modal-demo",
    type: "registry:block",
    registryDependencies: ["modal"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-demo")),
    source: "",
  },
  "tabs-demo": {
    name: "tabs-demo",
    type: "registry:block",
    registryDependencies: ["tabs","x-scrollable"],
    tags: [],
    files: [
      {
        path: "registry/examples/tabs-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tabs-demo")),
    source: "",
  },
  "scramble-text-demo": {
    name: "scramble-text-demo",
    type: "registry:block",
    registryDependencies: ["scramble-text"],
    tags: [],
    files: [
      {
        path: "registry/examples/scramble-text-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/scramble-text-demo")),
    source: "",
  },
  "use-copy-to-clipboard-demo": {
    name: "use-copy-to-clipboard-demo",
    type: "registry:block",
    registryDependencies: ["use-copy-to-clipboard"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-copy-to-clipboard-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-copy-to-clipboard-demo")),
    source: "",
  },
  "use-interval-demo": {
    name: "use-interval-demo",
    type: "registry:block",
    registryDependencies: ["use-interval"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-interval-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-interval-demo")),
    source: "",
  },
  "use-timeout-demo": {
    name: "use-timeout-demo",
    type: "registry:block",
    registryDependencies: ["use-timeout"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-timeout-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-timeout-demo")),
    source: "",
  },
  "use-document-title-demo": {
    name: "use-document-title-demo",
    type: "registry:block",
    registryDependencies: ["use-document-title"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-document-title-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-document-title-demo")),
    source: "",
  },
  "use-mouse-position-demo": {
    name: "use-mouse-position-demo",
    type: "registry:block",
    registryDependencies: ["use-mouse-position"],
    tags: [],
    files: [
      {
        path: "registry/examples/use-mouse-position-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/use-mouse-position-demo")),
    source: "",
  },
  "otp-input-demo": {
    name: "otp-input-demo",
    type: "registry:block",
    registryDependencies: ["otp-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-demo")),
    source: "",
  },
  "text-input-demo": {
    name: "text-input-demo",
    type: "registry:block",
    registryDependencies: ["text-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/text-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/text-input-demo")),
    source: "",
  },
  "file-input-demo": {
    name: "file-input-demo",
    type: "registry:block",
    registryDependencies: ["file-input"],
    tags: [],
    files: [
      {
        path: "registry/examples/file-input-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/file-input-demo")),
    source: "",
  },
  "tabs-spotify-demo": {
    name: "tabs-spotify-demo",
    type: "registry:block",
    registryDependencies: ["tabs","x-scrollable"],
    tags: [],
    files: [
      {
        path: "registry/examples/tabs-spotify-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tabs-spotify-demo")),
    source: "",
  },
  "drawer-modern-demo": {
    name: "drawer-modern-demo",
    type: "registry:block",
    registryDependencies: ["drawer"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-modern-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-modern-demo")),
    source: "",
  },
  "backdrop-gradient-artistic-demo": {
    name: "backdrop-gradient-artistic-demo",
    type: "registry:block",
    registryDependencies: ["backdrop-gradient"],
    tags: [],
    files: [
      {
        path: "registry/examples/backdrop-gradient-artistic-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/backdrop-gradient-artistic-demo")),
    source: "",
  },
  "x-scrollable-colorful-demo": {
    name: "x-scrollable-colorful-demo",
    type: "registry:block",
    registryDependencies: ["x-scrollable"],
    tags: [],
    files: [
      {
        path: "registry/examples/x-scrollable-colorful-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/x-scrollable-colorful-demo")),
    source: "",
  },
  "smart-form-pill-demo": {
    name: "smart-form-pill-demo",
    type: "registry:block",
    registryDependencies: ["smart-form"],
    tags: [],
    files: [
      {
        path: "registry/examples/smart-form-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/smart-form-pill-demo")),
    source: "",
  },
  "code-snippet-theme-demo": {
    name: "code-snippet-theme-demo",
    type: "registry:block",
    registryDependencies: ["code-snippet"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-snippet-theme-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-snippet-theme-demo")),
    source: "",
  },
  "code-snippet-options-demo": {
    name: "code-snippet-options-demo",
    type: "registry:block",
    registryDependencies: ["code-snippet"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-snippet-options-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-snippet-options-demo")),
    source: "",
  },
  "code-snippet-cpp-demo": {
    name: "code-snippet-cpp-demo",
    type: "registry:block",
    registryDependencies: ["code-snippet"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-snippet-cpp-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-snippet-cpp-demo")),
    source: "",
  },
  "code-snippet-adaptive-demo": {
    name: "code-snippet-adaptive-demo",
    type: "registry:block",
    registryDependencies: ["code-snippet"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-snippet-adaptive-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-snippet-adaptive-demo")),
    source: "",
  },
  "code-snippet-tabs-demo": {
    name: "code-snippet-tabs-demo",
    type: "registry:block",
    registryDependencies: ["code-snippet"],
    tags: [],
    files: [
      {
        path: "registry/examples/code-snippet-tabs-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/code-snippet-tabs-demo")),
    source: "",
  },
  "modal-drop-demo": {
    name: "modal-drop-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/modal.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-drop-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-drop-demo")),
    source: "",
  },
  "modal-blur-demo": {
    name: "modal-blur-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/modal.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-blur-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-blur-demo")),
    source: "",
  },
  "drawer-right-demo": {
    name: "drawer-right-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/drawer.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-right-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-right-demo")),
    source: "",
  },
  "drawer-scrollable-demo": {
    name: "drawer-scrollable-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/drawer.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-scrollable-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-scrollable-demo")),
    source: "",
  },
  "drawer-left-demo": {
    name: "drawer-left-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/drawer.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/drawer-left-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/drawer-left-demo")),
    source: "",
  },
  "otp-input-pill-demo": {
    name: "otp-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/otp-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-pill-demo")),
    source: "",
  },
  "otp-input-autofill-demo": {
    name: "otp-input-autofill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/otp-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-autofill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-autofill-demo")),
    source: "",
  },
  "otp-input-numeric-demo": {
    name: "otp-input-numeric-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/otp-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-numeric-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-numeric-demo")),
    source: "",
  },
  "select-input-pill-demo": {
    name: "select-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/select-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/select-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/select-input-pill-demo")),
    source: "",
  },
  "admonition-types-demo": {
    name: "admonition-types-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/admonition-types-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/admonition-types-demo")),
    source: "",
  },
  "admonition-custom-demo": {
    name: "admonition-custom-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/admonition.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/admonition-custom-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/admonition-custom-demo")),
    source: "",
  },
  "switch-input-pill-demo": {
    name: "switch-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/switch-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/switch-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/switch-input-pill-demo")),
    source: "",
  },
  "switch-input-standalone-demo": {
    name: "switch-input-standalone-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/switch-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/switch-input-standalone-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/switch-input-standalone-demo")),
    source: "",
  },
  "switch-input-color-demo": {
    name: "switch-input-color-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/switch-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/switch-input-color-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/switch-input-color-demo")),
    source: "",
  },
  "switch-input-sizes-demo": {
    name: "switch-input-sizes-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/switch-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/switch-input-sizes-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/switch-input-sizes-demo")),
    source: "",
  },
  "qr-code-custom-demo": {
    name: "qr-code-custom-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/qr-code.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/qr-code-custom-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/qr-code-custom-demo")),
    source: "",
  },
  "tags-input-pill-demo": {
    name: "tags-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/tags-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/tags-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tags-input-pill-demo")),
    source: "",
  },
  "qr-code-reactive-demo": {
    name: "qr-code-reactive-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/qr-code.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/qr-code-reactive-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/qr-code-reactive-demo")),
    source: "",
  },
  "tags-input-max-demo": {
    name: "tags-input-max-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/tags-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/tags-input-max-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tags-input-max-demo")),
    source: "",
  },
  "textarea-input-pill-demo": {
    name: "textarea-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/textarea-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/textarea-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/textarea-input-pill-demo")),
    source: "",
  },
  "textarea-input-max-demo": {
    name: "textarea-input-max-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/textarea-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/textarea-input-max-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/textarea-input-max-demo")),
    source: "",
  },
  "file-input-pill-demo": {
    name: "file-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/file-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/file-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/file-input-pill-demo")),
    source: "",
  },
  "file-input-multiple-demo": {
    name: "file-input-multiple-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/file-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/file-input-multiple-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/file-input-multiple-demo")),
    source: "",
  },
  "file-input-preview-demo": {
    name: "file-input-preview-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/file-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/file-input-preview-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/file-input-preview-demo")),
    source: "",
  },
  "text-input-pill-demo": {
    name: "text-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/text-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/text-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/text-input-pill-demo")),
    source: "",
  },
  "otp-input-short-demo": {
    name: "otp-input-short-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/otp-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-short-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-short-demo")),
    source: "",
  },
  "modal-custom-header-demo": {
    name: "modal-custom-header-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/modal.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-custom-header-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-custom-header-demo")),
    source: "",
  },
  "modal-no-overlay-close-demo": {
    name: "modal-no-overlay-close-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/modal.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-no-overlay-close-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-no-overlay-close-demo")),
    source: "",
  },
  "floating-object-compass-demo": {
    name: "floating-object-compass-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/floating-object.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/floating-object-compass-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/floating-object-compass-demo")),
    source: "",
  },
  "floating-object-multiple-demo": {
    name: "floating-object-multiple-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/floating-object.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/floating-object-multiple-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/floating-object-multiple-demo")),
    source: "",
  },
  "tabs-pills-demo": {
    name: "tabs-pills-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/tabs.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/tabs-pills-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tabs-pills-demo")),
    source: "",
  },
  "modal-minimal-demo": {
    name: "modal-minimal-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/modal.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/modal-minimal-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/modal-minimal-demo")),
    source: "",
  },
  "otp-input-validation-demo": {
    name: "otp-input-validation-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/otp-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/otp-input-validation-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/otp-input-validation-demo")),
    source: "",
  },
  "animate-in-hero-demo": {
    name: "animate-in-hero-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/animate-in.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-hero-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-hero-demo")),
    source: "",
  },
  "animate-in-stagger-demo": {
    name: "animate-in-stagger-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/animate-in.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-stagger-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-stagger-demo")),
    source: "",
  },
  "animate-in-directions-demo": {
    name: "animate-in-directions-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/animate-in.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-directions-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-directions-demo")),
    source: "",
  },
  "radio-input-pill-demo": {
    name: "radio-input-pill-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/radio-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/radio-input-pill-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/radio-input-pill-demo")),
    source: "",
  },
  "radio-input-icons-demo": {
    name: "radio-input-icons-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/radio-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/radio-input-icons-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/radio-input-icons-demo")),
    source: "",
  },
  "social-icons-monochrome-demo": {
    name: "social-icons-monochrome-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/social-icons.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/social-icons-monochrome-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/social-icons-monochrome-demo")),
    source: "",
  },
  "embed-blocked-demo": {
    name: "embed-blocked-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/embed.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/embed-blocked-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/embed-blocked-demo")),
    source: "",
  },
  "tabs-sizes-demo": {
    name: "tabs-sizes-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/tabs.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/tabs-sizes-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/tabs-sizes-demo")),
    source: "",
  },
  "scramble-text-intersection-demo": {
    name: "scramble-text-intersection-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/scramble-text.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/scramble-text-intersection-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/scramble-text-intersection-demo")),
    source: "",
  },
  "scramble-text-albums-demo": {
    name: "scramble-text-albums-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/scramble-text.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/scramble-text-albums-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/scramble-text-albums-demo")),
    source: "",
  },
  "radio-input-no-selection-demo": {
    name: "radio-input-no-selection-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/radio-input.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/radio-input-no-selection-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/radio-input-no-selection-demo")),
    source: "",
  },
  "animate-in-scale-demo": {
    name: "animate-in-scale-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/animate-in.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-scale-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-scale-demo")),
    source: "",
  },
  "smart-form-registration-demo": {
    name: "smart-form-registration-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/smart-form.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/smart-form-registration-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/smart-form-registration-demo")),
    source: "",
  },
  "dropdown-menu-profile-demo": {
    name: "dropdown-menu-profile-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/dropdown-menu.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/dropdown-menu-profile-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/dropdown-menu-profile-demo")),
    source: "",
  },
  "dropdown-menu-positions-demo": {
    name: "dropdown-menu-positions-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/dropdown-menu.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/dropdown-menu-positions-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/dropdown-menu-positions-demo")),
    source: "",
  },
  "animate-in-intersection-demo": {
    name: "animate-in-intersection-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/animate-in.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-intersection-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-intersection-demo")),
    source: "",
  },
  "animate-in-fade-demo": {
    name: "animate-in-fade-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/animate-in.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/animate-in-fade-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/animate-in-fade-demo")),
    source: "",
  },
  "bottom-bar-demo": {
    name: "bottom-bar-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/bottom-bar.json","bottom-bar"],
    tags: [],
    files: [
      {
        path: "registry/examples/bottom-bar-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/bottom-bar-demo")),
    source: "",
  },
  "bottom-bar-center-demo": {
    name: "bottom-bar-center-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/bottom-bar.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/bottom-bar-center-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/bottom-bar-center-demo")),
    source: "",
  },
  "bottom-bar-labels-demo": {
    name: "bottom-bar-labels-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/bottom-bar.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/bottom-bar-labels-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/bottom-bar-labels-demo")),
    source: "",
  },
  "toast-demo": {
    name: "toast-demo",
    type: "registry:block",
    registryDependencies: ["toast"],
    tags: [],
    files: [
      {
        path: "registry/examples/toast-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/toast-demo")),
    source: "",
  },
  "toast-positions-demo": {
    name: "toast-positions-demo",
    type: "registry:block",
    registryDependencies: ["toast"],
    tags: [],
    files: [
      {
        path: "registry/examples/toast-positions-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/toast-positions-demo")),
    source: "",
  },
  "toast-actions-demo": {
    name: "toast-actions-demo",
    type: "registry:block",
    registryDependencies: ["toast"],
    tags: [],
    files: [
      {
        path: "registry/examples/toast-actions-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/toast-actions-demo")),
    source: "",
  },
  "toast-custom-demo": {
    name: "toast-custom-demo",
    type: "registry:block",
    registryDependencies: ["toast"],
    tags: [],
    files: [
      {
        path: "registry/examples/toast-custom-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/toast-custom-demo")),
    source: "",
  },
  "toast-colors-demo": {
    name: "toast-colors-demo",
    type: "registry:block",
    registryDependencies: ["toast"],
    tags: [],
    files: [
      {
        path: "registry/examples/toast-colors-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/toast-colors-demo")),
    source: "",
  },
  "latex-demo": {
    name: "latex-demo",
    type: "registry:block",
    registryDependencies: ["latex"],
    tags: [],
    files: [
      {
        path: "registry/examples/latex-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/latex-demo")),
    source: "",
  },
  "latex-equations-demo": {
    name: "latex-equations-demo",
    type: "registry:block",
    registryDependencies: ["latex"],
    tags: [],
    files: [
      {
        path: "registry/examples/latex-equations-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/latex-equations-demo")),
    source: "",
  },
  "latex-enhanced-demo": {
    name: "latex-enhanced-demo",
    type: "registry:block",
    registryDependencies: ["latex"],
    tags: [],
    files: [
      {
        path: "registry/examples/latex-enhanced-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/latex-enhanced-demo")),
    source: "",
  },
  "marquee-basic-demo": {
    name: "marquee-basic-demo",
    type: "registry:block",
    registryDependencies: ["https://deltacomponents.dev/r/marquee.json"],
    tags: [],
    files: [
      {
        path: "registry/examples/marquee-basic-demo.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/examples/marquee-basic-demo")),
    source: "",
  },
  "animate-in": {
    name: "animate-in",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/animations/animate-in.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/animations/animate-in")),
    source: "",
  },
  "font-transform": {
    name: "font-transform",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/animations/font-transform.tsx",
        type: "registry:component",
        target: "",
      },
      {
        path: "registry/animations/font-transform.css",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/animations/font-transform")),
    source: "",
  },
  "floating-object": {
    name: "floating-object",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/animations/floating-object.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/animations/floating-object")),
    source: "",
  },
  "scramble-text": {
    name: "scramble-text",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["animation","text","scramble","effect","motion","interaction","reveal"],
    files: [
      {
        path: "registry/animations/scramble-text.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/animations/scramble-text")),
    source: "",
  },
  "marquee": {
    name: "marquee",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/components/marquee.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/marquee")),
    source: "",
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["dropdown","menu","overlay","popup","animated","accessible","positioning","component"],
    files: [
      {
        path: "registry/components/dropdown-menu.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/dropdown-menu")),
    source: "",
  },
  "social-icons": {
    name: "social-icons",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/components/social-icons.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/social-icons")),
    source: "",
  },
  "pricing-cards": {
    name: "pricing-cards",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/components/pricing-cards.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/pricing-cards")),
    source: "",
  },
  "star-rating": {
    name: "star-rating",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["star","rating","feedback","interactive","component"],
    files: [
      {
        path: "registry/components/star-rating.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/star-rating")),
    source: "",
  },
  "retro-button": {
    name: "retro-button",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["button","retro","ui","component"],
    files: [
      {
        path: "registry/components/retro-button.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/retro-button")),
    source: "",
  },
  "admonition": {
    name: "admonition",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["admonition","alert","info","component"],
    files: [
      {
        path: "registry/components/admonition.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/admonition")),
    source: "",
  },
  "embed": {
    name: "embed",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["embed","iframe","media","component"],
    files: [
      {
        path: "registry/components/embed.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/embed")),
    source: "",
  },
  "scroll-progress": {
    name: "scroll-progress",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["scroll","progress","indicator","component"],
    files: [
      {
        path: "registry/components/scroll-progress.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/scroll-progress")),
    source: "",
  },
  "drawer": {
    name: "drawer",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["overlay","panel","slide","bottom sheet","dialog","mobile","responsive","component"],
    files: [
      {
        path: "registry/components/drawer.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/drawer")),
    source: "",
  },
  "modal": {
    name: "modal",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["dialog","popup","overlay","animated","accessible","responsive","component"],
    files: [
      {
        path: "registry/components/modal.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/modal")),
    source: "",
  },
  "tabs": {
    name: "tabs",
    type: "registry:component",
    registryDependencies: ["x-scrollable"],
    tags: ["navigation","tabs","interactive","animated","scrollable","content switcher","component"],
    files: [
      {
        path: "registry/components/tabs.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/tabs")),
    source: "",
  },
  "x-scrollable": {
    name: "x-scrollable",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["scroll","horizontal","container","utility","layout","component"],
    files: [
      {
        path: "registry/components/x-scrollable.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/x-scrollable")),
    source: "",
  },
  "toast": {
    name: "toast",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["notification","toast","alert","feedback","themed","positioning","accessible","component"],
    files: [
      {
        path: "registry/components/toast.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/components/toast")),
    source: "",
  },
  "smart-form": {
    name: "smart-form",
    type: "registry:block",
    registryDependencies: ["text-input","checkbox-input","select-input","radio-input","switch-input","textarea-input","date-input","file-input","otp-input","tags-input"],
    tags: ["form","dynamic","smart","validation","reactive","data collection","AI","block"],
    files: [
      {
        path: "registry/blocks/smart-form.tsx",
        type: "registry:block",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/blocks/smart-form")),
    source: "",
  },
  "mouse-string-connection": {
    name: "mouse-string-connection",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/landing-page/mouse-string-connection.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/landing-page/mouse-string-connection")),
    source: "",
  },
  "highlighter": {
    name: "highlighter",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["highlight","text","landing","animation","component"],
    files: [
      {
        path: "registry/landing-page/highlighter.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/landing-page/highlighter")),
    source: "",
  },
  "youtube": {
    name: "youtube",
    type: "registry:component",
    registryDependencies: ["use-mobile"],
    tags: [],
    files: [
      {
        path: "registry/media/youtube.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/youtube")),
    source: "",
  },
  "cambio-image": {
    name: "cambio-image",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/media/cambio-image.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/cambio-image")),
    source: "",
  },
  "qr-code": {
    name: "qr-code",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/media/qr-code.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/qr-code")),
    source: "",
  },
  "spotify": {
    name: "spotify",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["spotify","audio","media","component"],
    files: [
      {
        path: "registry/media/spotify.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/spotify")),
    source: "",
  },
  "backdrop-gradient": {
    name: "backdrop-gradient",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["effect","image","blur","gradient","background","filter"],
    files: [
      {
        path: "registry/media/backdrop-gradient.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/backdrop-gradient")),
    source: "",
  },
  "retro-video-player": {
    name: "retro-video-player",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["video","player","draggable","resizable","retro","ui","media"],
    files: [
      {
        path: "registry/media/retro-video-player.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/retro-video-player")),
    source: "",
  },
  "code-snippet": {
    name: "code-snippet",
    type: "registry:component",
    registryDependencies: ["button"],
    tags: ["syntax highlighting","code","copyable","lightweight","developer"],
    files: [
      {
        path: "registry/media/code-snippet.tsx",
        type: "registry:component",
        target: "",
      },
      {
        path: "registry/media/copy-button.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/code-snippet")),
    source: "",
  },
  "latex": {
    name: "latex",
    type: "registry:component",
    registryDependencies: undefined,
    tags: ["latex","math","mathematical","equations","katex","typography","scientific","academic"],
    files: [
      {
        path: "registry/media/latex.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/media/latex")),
    source: "",
  },
  "header-sleek": {
    name: "header-sleek",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/layout/header-sleek.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/layout/header-sleek")),
    source: "",
  },
  "footer": {
    name: "footer",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/layout/footer.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/layout/footer")),
    source: "",
  },
  "bottom-bar": {
    name: "bottom-bar",
    type: "registry:component",
    registryDependencies: undefined,
    tags: [],
    files: [
      {
        path: "registry/layout/bottom-bar.tsx",
        type: "registry:component",
        target: "",
      }
    ],
    component: React.lazy(() => import("@/registry/layout/bottom-bar")),
    source: "",
  },
}
